# Build modules specific to RockChip.

SUBDIR = \
	../usbc \
	../fusb302 \
	rk_cdn_dp \
	rk_drm \
	rk_i2c \
	rk3399_dptx_fw \
	rk3399_power \
	rk3399_typec_altmode_helper \
	rk3399_tcphy_helper \
	rk805 \
	rk808 \
	rk_dwmmc \
	rk_spi

.include <bsd.subdir.mk>
